### ISSUE TITLE
what is mcpypath

### ISSUE THREAD

**Issue by BhavayJ** [jason-bowen-zheng/Minecraft#4]
bro, I am a programmer and I cant understand what you mean by mcpypath also it is showing error in minecraft/source.py   that mcpypath is not defined. so what is that please tell or please change the source.py

**Comment by BhavayJ** [comment]
in english only

**Comment by ismaelxyz** [comment]
MCPYPATH (Not mcpypath ) is an [environment variable](https://en.wikipedia.org/wiki/Environment_variable) that you have to declare, the way you
declare an environment variable varies according to your operating system.

In the path linked to MCPYPATH are saved files of 
a lot of value for the good functioning of the programme.

The value of MCPYPATH should be the place where you can save these important files in my case
$HOME/PyMinecr (I use [Deepin OS](https://www.deepin.org/en/))

If you tell me what your operating system is, I can explain in detail how to create an environment
variable.

**Comment by ismaelxyz** [comment]
This issues was solved, the user can create an environment variable with the name MCPYPATH and
it value will be the path to a directory or let the game assign it a default one.

This folder will be used by Minecraft for complex operations.

**Comment by jason-bowen-zheng** [comment]
So can I close it?
